ci: tests: generic: ulimit: fix racy check on nec-wx3000hp
Fixes following random CI testing failure on nec-wx3000hp:

  ERROR: unlimited core size detected: ubus wait_for -t 60 NetModel.Intf

This command was introduced in feed-prpl's commit a33007609f7a
("tr181-dhcpv4client: nec-wx3000hp: workaround missing nedev-up flag on
wan interface"), where the workaround fix is fiddling with wan interface
operstate flags.

References: References: PCF-703
References: https://gitlab.com/prpl-foundation/prplos/prplos/-/jobs/3097748190
Fixes: b26253086d3d ("ci: tests: generic: assure no unlimited core file shell resource limits")
Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit efd1bd98480be36dfdd50c8e5421f6df246b3c90)