ci: tests: ulimit.t: whitelist hostapd and wpa_supplicant processes
CI currently reports following issues:

 ERROR: unlimited core size detected: /sbin/ujail -t 5 -n hostapd -U network -G network -C /etc/capabilities/wpad.json -c -- /usr/sbin/hostapd -s -g /var/run/hostapd/global
 ERROR: unlimited core size detected: /sbin/ujail -t 5 -n wpa_supplicant -U network -G network -C /etc/capabilities/wpad.json -c -- /usr/sbin/wpa_supplicant -n -s -g /var/run/wpa_supplicant/global
 ERROR: unlimited core size detected: /usr/sbin/hostapd -s -g /var/run/hostapd/global
 ERROR: unlimited core size detected: /usr/sbin/wpa_supplicant -n -s -g /var/run/wpa_supplicant/global

Which is expected and very well tested upstream, so lets whitelist those
processes and while at it, convert the `grep` matching into the regexp
to make it shorter.

References: PCF-663
References: https://gitlab.com/prpl-foundation/prplos/prplos/-/jobs/6719417516#L133
Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>