PROVISORY: profiles: mxl: workaround OpenSSL 3 and GCC 12.3.0 build issues
There are currently several UPDK packages failing to build due to
OpenSSL 3.0 API deprecations or a new `-Werror=address` flag enabled in
GCC 12.3.0:

 ERROR: package/feeds/ugw_sdk/libscapi failed to build.

   scapi_nslookup.c: In function 'scapi_nslookup':
   scapi_nslookup.c:388:21: error: the comparison will always evaluate as 'true' for the address of 'dnsserver' will never be NULL [-Werror=address]
    388 |                 if (pxNSLookupQuery->dnsserver)
        |                     ^~~~~~~~~~~~~~~

 ERROR: package/feeds/ppa/ppa-drv failed to build.

   ppa-drv-4.2.3.50/src/ppa_api/ppa_api_session.c: In function 'ppa_mc_check_dst_itf':
   ppa-drv-4.2.3.50/src/ppa_api/ppa_api_session.c:3423:47: error: the comparison will always evaluate as 'true' for the address of 'array_mem_ifs' will never be NULL [-Werror=address]
   3423 |                 if (p_mc_group->array_mem_ifs != NULL) {
        |                                               ^~

 ERROR: package/feeds/pon/gpon-omci-onu failed to build.

  ../../src/omci_mic_check.c: In function 'omci_mic_cmac_calc':
  ../../src/omci_mic_check.c:117:9: error: 'CMAC_CTX_new' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   117 |         CMAC_CTX *ssl_ctx = CMAC_CTX_new();
       |         ^~~~~~~~

 ERROR: package/feeds/wlan_6x/iwlwav-hostap-ng-uci failed to build (build variant: release)

  ../src/crypto/tls_openssl.c: In function 'tls_connection_private_key':
  ../src/crypto/tls_openssl.c:3827:17: warning: 'SSL_use_RSAPrivateKey_ASN1' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
   3827 |                 if (SSL_use_RSAPrivateKey_ASN1(conn->ssl,
        |                 ^~

So lets workaround those issues by gloabal
`-Wno-error=deprecated-declarations -Wno-error=address` compiler flags
until those issues are fixed.

References: PCF-1169
Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>