profiles: prpl: tr181-xpon.sh: make core size configurable
CI currently reports, that component has unlimited core size enabled:

 ERROR: unlimited core size detected: tr181-xpon -D

So lets fix it by making it disabled by default and configurable via
/etc/environment and thus keep in sync with other prplWare components.

Fixes: PCF-1188
References: PCF-663
References: https://gitlab.com/prpl-foundation/prplos/prplos/-/jobs/6719417516#L133
Upstream-Status: Submitted [https://gitlab.com/prpl-foundation/components/core/plugins/tr181-xpon/-/merge_requests/2]
Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>