ci: docker: sdk: fix build test issue with OpenWrt 22.03
Currently SDK container build test fails:

 tmp/.config-package.in:7:warning: ignoring type redefinition of 'PACKAGE_busybox' from 'bool' to 'tristate'
 feeds/base/package/utils/busybox/config/Config.in:697: syntax error

Fix it by using proper base container and prplOS base feed, also use
urngd for build testing as it seems, that busybox can't be currently
build:

 include/libbb.h:83:11: fatal error: selinux/selinux.h: No such file or directory
   83 | # include <selinux/selinux.h>
      |           ^~~~~~~~~~~~~~~~~~~

Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit 2ff97d72962d661b8ae208b6e0bb4f7802a8ed93)