ci:coverity: fix uboot-tools cov-build failure.
uboot-tools (pylibfdt) failed to compile with:
fatal error: Python.h: No such file or directory

Add python3-dev to the apt-get install step to provide the
missing header.

Reference: PPW-2121
Signed-off-by: Mouna Aloui <mouna.aloui@softathome.com>