PROVISORY: profiles: qca_ipq95xx: fix qca-nss-dscpstats build by enabling DYNAMIC_DEBUG
Currently qca-nss-dscpstats fails to build:

  CC [M]  /builds/prpl-foundation/prplos/prplos/build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/linux-ipq95xx_generic/qca-nss-dscpstats-35f8409213188c5f2d820740b4b74eddf8c7a379/nss_dscpstats.o
  In file included from /builds/prpl-foundation/prplos/prplos/build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/linux-ipq95xx_generic/qca-nss-dscpstats-35f8409213188c5f2d820740b4b74eddf8c7a379/nss_dscpstats.c:21:
   /builds/prpl-foundation/prplos/prplos/build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/linux-ipq95xx_generic/qca-nss-dscpstats-35f8409213188c5f2d820740b4b74eddf8c7a379/nss_dscpstats.h:35:6: error: "nss_dscpstats_DEBUG_LEVEL" is not defined, evaluates to 0 [-Werror=undef]
    35 | #if (nss_dscpstats_DEBUG_LEVEL < 2)
       |      ^~~~~~~~~~~~~~~~~~~~~~~~~

as the code depends on having DYNAMIC_DEBUG=y enabled and fails to build
without it. So lets enable this kernel config option until the
underlying issue is fixed.

References: PCF-1966
Link: https://gitlab.com/prpl-foundation/prplos/prplos/-/jobs/10895303289#L8677
Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>