WIP: ci: remove package and feed integrity checks
The CI build pipelines currently fail if any downloaded package source or
feed package is dirty or has its hashes updated during the build, which
prevents builds from succeeding when feeds or packages are modified in
a branch without their updated hashes checked in.

Currently, the CI pipeline runs `make download check FIXUP=1` which
automatically corrects package and feed Makefile hashes, causing git to
detect modified files. Then the integrity check stage checks if the git
status is dirty and exits with a failure if so.

So lets remove the package and feed integrity checks from the CI
pipelines, and simplify the download targets to not run the checks
and fixups.

Log evidence of the failure:
Feed feeds/feed_prplmesh packages integrity issues, please check the output bellow or feed-packages-hash-issues.patch from artifacts
diff --git a/services/prplmesh-dm-mapper/Makefile b/services/prplmesh-dm-mapper/Makefile
index 1d83280..cefcfbf 100644
--- a/services/prplmesh-dm-mapper/Makefile
+++ b/services/prplmesh-dm-mapper/Makefile
@@ -7,7 +7,7 @@ PKG_RELEASE:=1
 PKG_SOURCE_PROTO:=git
 PKG_SOURCE_VERSION:=PPW-1951-hide-vendor-data-elements-causing-obuspa-and-ubus-datamodel-list-cram-test-failures
 PKG_SOURCE_URL:=https://gitlab.com/prpl-foundation/prplmesh/prplmesh-dm-mapper.git
-PKG_MIRROR_HASH:=skip
+PKG_MIRROR_HASH:=12ac1f11a27792438cc691d30824a481845bbe0ea7e6ccc1903f043f268340c0
 PKG_BUILD_DIR:=$(BUILD_DIR)/$(PKG_NAME)-$(PKG_VERSION)

 include $(INCLUDE_DIR)/package.mk
ERROR: Job failed: exit code 1

Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>