PROVISORY: prpl: config: disable KERNEL_WERROR on ipq95xx target
ATH 12.4.0 CS kernel 6.1.31 with CONFIG_WERROR=y using GCC 12.3.0 contains following issues:

 drivers/net/mdio/mdio-ipq4019.c:756:72: error: passing argument 2 of 'of_get_next_available_child' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
 net/ipv6/ip6mr.c:531:44: error: format '%llu' expects argument of type 'long long unsigned int', but argument 5 has type 'long unsigned int' [-Werror=format=]
 net/ipv6/ip6mr.c:531:50: error: format '%llu' expects argument of type 'long long unsigned int', but argument 6 has type 'long unsigned int' [-Werror=format=]
 net/ipv6/ip6mr.c:531:57: error: format '%llu' expects argument of type 'long long unsigned int', but argument 7 has type 'long unsigned int' [-Werror=format=]
 net/ipv6/ip6mr.c:531:63: error: format '%llu' expects argument of type 'long long unsigned int', but argument 8 has type 'long unsigned int' [-Werror=format=]
 drivers/mtd/nand/raw/qcom_nandc.c:326:78: error: excess elements in struct initializer [-Werror]
 drivers/firmware/qcom_scm.c:2916:9: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
 net/ipv4/ipmr.c:3174:44: error: format '%llu' expects argument of type 'long long unsigned int', but argument 5 has type 'long unsigned int' [-Werror=format=]
 net/ipv4/ipmr.c:3174:50: error: format '%llu' expects argument of type 'long long unsigned int', but argument 6 has type 'long unsigned int' [-Werror=format=]
 net/ipv4/ipmr.c:3174:57: error: format '%llu' expects argument of type 'long long unsigned int', but argument 7 has type 'long unsigned int' [-Werror=format=]
 net/ipv4/ipmr.c:3174:63: error: format '%llu' expects argument of type 'long long unsigned int', but argument 8 has type 'long unsigned int' [-Werror=format=]

So until that gets fixed, we need to disable KERNEL_WERROR config option
temporarily on ipq95xx target, thus we still keep the QA on the other
targets.

References: PCF-1228
Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>