profiles: prpl: prplmesh: fix Python3 and YAML handling
Update containing following changes:

* prplmesh: backport FindPython3 CMake handling

  Backport of commit b6d664c544cd ("Use FindPython3 to find python3")

* prplmesh: fix Python3 and YAML handling

  prplMesh needs Python3 YAML module for automatic generation of TLVF
  library. In prplOS we're using Python3 YAML module installed on the host
  as implicit and mandatory build prerequisite.

  That works fine unless there is python3/host OpenWrt package present on
  the build system, in those cases CMake simply finds that interpreter
  first and prplMesh fails to build as there is usually YAML module
  missing:

    ModuleNotFoundError: No module named 'yaml.constructor'

  So lets fix it by making the Python3 YAML module host dependency
  explicit and assure usage of same Python3 interpreter in CMake as well.

Fixes: PCF-923
Signed-off-by: Petr Štetiar <ynezz@true.cz>