PROVISORY: profiles: prpl: enable -Wno-error=address to workaround compilation issues
The following errors are seen in libscapi when building for the mxl osp V1 platform:
scapi_nslookup.c: In function 'scapi_nslookup':
scapi_nslookup.c:388:21: error: the comparison will always evaluate as 'true' for the address of 'dnsserver' will never be NULL [-Werror=address]
  388 |                 if (pxNSLookupQuery->dnsserver)
      |                     ^~~~~~~~~~~~~~~
In file included from ./include/ltq_api_include.h:29,
                 from scapi_nslookup.c:41:
./include/scapi_structs.h:150:15: note: 'dnsserver' declared here
  150 |         char8 dnsserver[MAX_HOST_NAME];    /*!< DNS Server Name or IP */
      |               ^~~~~~~~~
scapi_nslookup.c:423:28: error: the comparison will always evaluate as 'true' for the address of 'address' will never be NULL [-Werror=address]
  423 |                 if(address != NULL)
      |                            ^~
scapi_nslookup.c:358:24: note: 'address' declared here
  358 |         char buff[30], address[256] = { 0 };
      |                        ^~~~~~~
cc1: all warnings being treated as errors

This commit adds -Wno-error=address to the CFLAGS to surpress the warning for the time being.

-fno-caller-saves -fno-plt are added as well, since these are the defaults for this config option.

Signed-off-by: Matthias FRANCK <matthias.franck_ext@softathome.com>