PROVISORY: profiles: prpl: workaround missing OpenSSL 3.0.0 compatibility
Enable `-Wno-error=deprecated-declarations` globally so we can

  prplMesh-4.2.3/framework/common/encryption.cpp: In constructor 'mapf::encryption::diffie_hellman::diffie_hellman()':
  prplMesh-4.2.3/framework/common/encryption.cpp:98:18: error: 'DH* DH_new()' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
     98 |     m_dh = DH_new();
        |            ~~~~~~^~

References: PPM-2524
Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>