.gitlab: scripts: testbed-cdrouter.py: decode file as utf-8
When running the changes done in 140ad37e2ab09247efe42a2f1b6701a7586e14fe
We see:
Traceback (most recent call last):
  File ".gitlab/scripts/testbed-cdrouter.py", line 441, in <module>
    main()
  File ".gitlab/scripts/testbed-cdrouter.py", line 437, in main
    args.func(cdr)
  File ".gitlab/scripts/testbed-cdrouter.py", line 345, in config_import
    content = self.replace_env_config_variables(content)
  File ".gitlab/scripts/testbed-cdrouter.py", line 330, in replace_env_config_variables
    text = re.sub(pattern, value, text)
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

The reb.sub() command fails because a non utf-8 encoded string is passed. Let's therefore adapt the method that is called for opening a file to always return a utf-8 decoded string.

Signed-off-by: Matthias FRANCK <matthias.franck@softathome.com>