profiles: prpl: prplmesh: backport fixes for build issues with gcc 12.3.0
Currently its not possible to build controller and unit tests with
upcoming prplOS 3.1.0 release (OpenWrt 23.05 based) with GCC 12.3.0:

 prplMesh-4.2.3/controller/src/beerocks/master/controller.cpp: In member function 'void son::Controller::set_esp(const std::string&, const sMacAddr&, uint8_t*)':
 /prplos-23.05-haze/build_dir/target-aarch64_cortex-a53_musl/prplMesh-4.2.3/controller/src/beerocks/master/controller.cpp:1559:37: error: statement has no effect [-Werror=unused-value]
  1559 |     (estimated_service_param.bytes[2]);
       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~

 prplMesh-4.2.3/framework/tlvf/test/tlvf_test.cpp:1565:31: error: variable 'std::array<unsigned char, 2048> assoc_frame_body' has initializer but incomplete type
 1565 |     std::array<uint8_t, 2048> assoc_frame_body = {};
      |                               ^~~~~~~~~~~~~~~~

References: PPM-2828, PPM-2829
Signed-off-by: Dmytro Puz <d.puz@inango-systems.com>
Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>
(cherry picked from commit 2e5988367192bcebdf4a44b1c4ade499bc405e9d)