Revert "ci: sdk: workaround registry.gitlab.com issues"
This reverts commit 28b18ff4274219b15bd5633b1e73d53953de58b3 as the
workaround was not fully working, the runner was able to download the
container image, but then got banned by the host serving the artifacts:

 Downloading artifacts for generate (4302834381)...
 ERROR: Downloading artifacts from coordinator... forbidden  id=4302834381 responseStatus=403 Forbidden status=403 Forbidden token=64_bkzMh
 FATAL: permission denied

References: PCF-777
Signed-off-by: Petr Štetiar <ynezz@true.cz>