PROVISORY: profiles: prpl: amx-cli: fix compilation with musl libc 1.2.5
basename() prototype has been removed from string.h from the musl libc 1.2.5,
so amx-cli currently doesn't compile with GCC 13.3.0 due to the
following errors:

  main.c: In function 'main':
  main.c:233:29: error: implicit declaration of function 'basename' [-Werror=implicit-function-declaration]
    233 |     amx_cli_build_file_name(basename(argv[0]));
        |                             ^~~~~~~~
  main.c:233:29: error: nested extern declaration of 'basename' [-Werror=nested-externs]
  main.c:233:29: error: passing argument 1 of 'amx_cli_build_file_name' makes pointer from integer without a cast [-Werror=int-conversion]

So fix it by including the libgen.h, which provides the function
prototype.

References: PCF-1594
References: https://git.musl-libc.org/cgit/musl/commit/?id=725e17ed6dff4d0cd22487bb64470881e86a92e7
Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>