ci: testbed-cdrouter.py: fix re.sub decode issue by passing utf-8 string
When running the changes done in commit 140ad37e2ab0 ("cdrouter:
wireless: make wifiBeaconPhy configurable"), we can see:

Traceback (most recent call last):
  File ".gitlab/scripts/testbed-cdrouter.py", line 441, in <module>
    main()
  File ".gitlab/scripts/testbed-cdrouter.py", line 437, in main
    args.func(cdr)
  File ".gitlab/scripts/testbed-cdrouter.py", line 345, in config_import
    content = self.replace_env_config_variables(content)
  File ".gitlab/scripts/testbed-cdrouter.py", line 330, in replace_env_config_variables
    text = re.sub(pattern, value, text)
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object

The re.sub() command fails because a non utf-8 encoded string is
passed. Let's therefore adapt the method that is called for opening a
file to always return a utf-8 decoded string.

Fixes: 140ad37e2ab0 ("cdrouter: wireless: make wifiBeaconPhy configurable")
Signed-off-by: Matthias FRANCK <matthias.franck@softathome.com>
(cherry picked from commit c6392418d73e468d0328041db18069442e93acbc)