profiles: x86_64: fix hostapd build failure
hostapd currently fails to build:

   LD  hostapd_cli
  x86_64-openwrt-linux-musl/bin/ld: tmp/cclmuDyG.ltrans7.ltrans.o: in function `br_addif':
  <artificial>:(.text+0xf67): undefined reference to `linux_br_add_if'
  x86_64-openwrt-linux-musl/bin/ld: tmp/cclmuDyG.ltrans7.ltrans.o: in function `vlan_get_bridge':
  <artificial>:(.text+0x130d): undefined reference to `linux_br_add'
  x86_64-openwrt-linux-musl/bin/ld: tmp/cclmuDyG.ltrans7.ltrans.o: in function `br_delif':
  <artificial>:(.text+0x14d3): undefined reference to `linux_br_del_if'
  x86_64-openwrt-linux-musl/bin/ld: tmp/cclmuDyG.ltrans7.ltrans.o: in function `vlan_put_bridge':
  <artificial>:(.text+0x17b8): undefined reference to `linux_br_del'

as `CONFIG_DRIVER_NL80211=` is being passed empty because:

  CONFIG_DRIVER_NL80211=$(CONFIG_PACKAGE_kmod-cfg80211)

there is currently no wireless interface available on this target, thus
default kernel modules for wireless stack are missing. So lets fix it by
adding `kmod-mac80211-hwsim` kernel module.

References: https://gitlab.com/prpl-foundation/prplos/prplos/-/jobs/3645584819
Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit 2e7f009fbb6b924ff3aa2aa2cff6040c5971d10a)