profiles: x86_64: increase rootfs partition size to 130MB
After addition of prplMesh+pwhm it seems, that rootfs partition
occupation has grown by 30MB and thus current 104M rootfs partition size
is too small for this default configuration and build ends with:

 error: ext4_allocate_best_fit_partial: failed to allocate 38 blocks, out of space?

Squashfs reports following:

 Filesystem size 28126.08 Kbytes (27.47 Mbytes)
    27.50% of uncompressed filesystem size (102276.84 Kbytes)

so the filesystem is apparently at roughly 103MB, so fix it by
increasing the default rootfs partition size to 130MB which should
hopefully last for some time.

References: https://gitlab.com/prpl-foundation/prplos/prplos/-/jobs/3942299487
Signed-off-by: Petr Štetiar <ynezz@true.cz>