ci: testbed: turris-omnia: fix loading of larger initramfs images
Currently it's not possible to load 17M large initramfs as it seems,
that U-Boot can't decompress image due to memory overlapping:

 Uncompressing Kernel Image
 ERROR: new format image overwritten - must RESET the board to recover
 resetting ...

So fix it by loading the initramfs image by 16MB futher.

Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit 435839597c8bc718f12c44890c0cf2dae141338f)