profiles: mxl_x86_osp_tb341_v2: fix libubus.h: No such file or directory
Currently swpal_6x-uci package fails to compile randomly with following error:

  src/uci_wrapper.c:20:10: fatal error: libubus.h: No such file or directory
     20 | #include <libubus.h>
        |          ^~~~~~~~~~~

This was caused by missing dependency on libubus, which could result in a race
condition during the build process. It seems that both the ubus package and
swpal_6x-uci are being compiled simultaneously on different CPU threads. As a result,
the ubus headers might be installed later than needed by swpal_6x-uci,
leading to this very sporadic build failure.

This update fixes the issue by providing explicit package dependency on libubus.

Fixes: PCF-1391
Signed-off-by: Bhavesh Bharadiya <bnbharadiya@maxlinear.com>