ci: sdk: improve feed-prpl build testing
Currently pcm-manager package fails to build when SAH_AMX_PCM_TARBALL is
enabled:

 fs_utils.c:86:10: fatal error: libtar.h: No such file or directory
   86 | #include <libtar.h>
      |          ^~~~~~~~~~

as there is no `libtar` package available, but we didn't noticed this on
the CI as the SDK preserves build root's configuration, so this results
in Config-build.in with following config:

 config SAH_AMX_PCM_TARBALL
	bool
	default n

Which is then default and if the package later changes this to `default
y` like in this case, it has no effect during the built within the SDK.

So lets prevent similar situation in the future and simply remove all
SAH boolean config options from the SDK's Config-build.in and use the
package defaults.

References: PCF-1034
Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit 779b50c7fa4e5acb7228887b92c134163c780581)