ci: cdrouter: add check_connectivity command
Currently we're sometime seeing the following error:

  $ .gitlab/scripts/testbed-cdrouter.py package_stop
  Traceback (most recent call last):
  ...
  urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='<redacted>', port=80): Max retries exceeded with url: /api/v1/results/?filter=status~%28running%7Cpaused%29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6380682358>: Failed to establish a new connection: [Errno 113] No route to host'))

So lets add a `check_connectivity` command to , which uses exponential backoff
 retry logic to verify CDRouter API connectivity within a fixed 30 seconds timeout.

Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>
(cherry picked from commit 357923dfd22420953e40e64b2a613c175bd24a10)