ci: cdrouter-dut-flush-dns-relay-cache.sh: rename DNS.Relay.X_PRPL-COM_Config
After aligning the tr181-dns datamodel with the tr181 v2.18 datamodel,
the DNS.Relay.X_PRPL-COM_Config object no longer exists:

  Running .gitlab/scripts/dut-init/cdrouter-dut-flush-dns-relay-cache.sh
  Command failed: Request timed out
  > DNS.Relay.X_PRPL-COM_Config.[Alias=="lan"].FlushCache()
  ERROR: No objects found DNS.Relay.X_PRPL-COM_Config.[Alias=="lan"].FlushCache

So lets fix it by using the current DNS.Relay.Config without the prefix.

References: PCF-1492
Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>