build: Add KBUILD_HOSTLDLIBS
In Linux kernel commit 8377bd2b9ee1 ("kbuild: Rename HOST_LOADLIBES to
KBUILD_HOSTLDLIBS") HOST_LOADLIBES was renamed to KBUILD_HOSTLDLIBS.
This patch adapts the OpenWrt kernel build to this new variable. Without
this change the kernel host tools would not link against the libraries
found in the staging directory.

MXL is using 4.19 kernel where missing KBUILD_HOSTLDLIBS variable is
leading to following build linker failure when building extract-cert
tool:

 make[5]: Entering directory '/source/linux'
   CALL    scripts/checksyscalls.sh
   DESCEND  objtool
   HOSTCC  scripts/extract-cert
 ugw_sw/openwrt/tmp/cc7QnLMG.o: In function `main':
 extract-cert.c:(.text.startup+0x1e): undefined reference to `OPENSSL_add_all_algorithms_noconf'
 extract-cert.c:(.text.startup+0x23): undefined reference to `ERR_load_crypto_strings'

Here the kernel uses the header files from libressl which is provided in
the OpenWrt tools for compilation and then wants to link against the
libcrypto.so from OpenSSL provided by Ubuntu 18.04 in version 1.1.1
which does not provide some of these symbols. We should take the library
and the header files from the same source.

The issue is only visible when CONFIG_SYSTEM_TRUSTED_KEYRING is
activated in Kernel config. This is activated by
CONFIG_SYSTEM_DATA_VERIFICATION and this by
CONFIG_CFG80211_REQUIRE_SIGNED_REGDB which is probably needed by wifi
stack.

Signed-off-by: Hauke Mehrtens <hauke.mehrtens@intel.com>
Signed-off-by: Petr Štetiar <ynezz@true.cz> [prplOS related description]
(cherry picked from commit eec50c73c4c9cca89a4bca13a40517b262192fea)
(cherry picked from commit 5d851843387298f406c00670138de6cc7f512435)