ci: testbed: turris-omnia: fix loading of larger initramfs images
It's not possible to load larger initramfs images (18.2MB):

  => bootm ${kernel_addr_r}
  ## Loading kernel from FIT Image at 01000000 ...
     Using 'config-1' configuration
     Trying 'kernel-1' kernel subimage
       Description:  ARM OpenWrt Linux-5.15.58
       ...snip...
       Data Start:   0x010000e4
       Data Size:    19032791 Bytes = 18.2 MiB
       ...snip...
     Uncompressing Kernel Image
  ERROR: new format image overwritten - must RESET the board to recover

Fix it by tftpbooting onto address 0x2000000 from current 0x1000000
which should leave enough room for future.

Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit a7343e70441c42be20e505194ae237ae6e3dd716)