PROVISORY: profiles: prpl: libswla: fix compilation with musl libc 1.2.5
basename() prototype has been removed from string.h from the musl libc 1.2.5,
so libswla currently doesn't compile with GCC 13.3.0 due to the
following errors:

  swla_exec.c:217:8: error: implicit declaration of function 'basename'; did you mean 'rename'? [-Werror=implicit-function-declaration]
    217 |     if(basename(prgCopy) != prgCopy) {
        |        ^~~~~~~~
        |        rename
  swla_exec.c:217:26: error: comparison between pointer and integer [-Werror]
    217 |     if(basename(prgCopy) != prgCopy) {
        |                          ^~

So fix it by including the libgen.h, which provides the function
prototype.

References: PCF-1597
References: https://git.musl-libc.org/cgit/musl/commit/?id=725e17ed6dff4d0cd22487bb64470881e86a92e7
Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>