PROVISORY: ci: drop Turris Omnia jobs from stable-4.2
Stable-4.2 release prep currently fails in the
build test mvebu prpl security job from the prplware-v4.2.0 tag
pipeline because obuspa v10.0.14 does not build on that target:

src/core/database.c:957:23: error: format '%ld' expects argument
of type 'long int', but argument 6 has type 'off_t'
{aka 'long long int'} [-Werror=format]
ERROR: package/feeds/feed_prplos/obuspa failed to build.

Until PPW-1642 is fixed, remove the Turris Omnia CI/release path
from stable-4.2 so release prep can proceed without the failing
mvebu jobs. This drops the Turris testbed/CDRouter jobs,
release artifacts, and mvebu SDK/IB/LCM container jobs from this
branch only.

References: PPW-1642
Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>