tools: m4: fix build breakage with recent glibc versions
Fixes following build failure in m4 v1.4.18 when building with recent
glibc version:

 In file included from /usr/include/signal.h:328,
                 from ./signal.h:52,
                 from c-stack.c:49:
 c-stack.c:55:26: error: missing binary operator before token "("
   55 | #elif HAVE_LIBSIGSEGV && SIGSTKSZ < 16384

It's been proposed to stop making SIGSTKSZ an integer constant:
https://sourceware.org/pipermail/libc-alpha/2020-September/118028.html

Fix it by backporting Debian patch.

Fixes: PCF-814
References: https://github.com/openwrt/openwrt/issues/9055
Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit e9d33ba7e724f01292cf1a59746a2712a83021da)