ci: sdk: fix build breakage by using packaged jinja2
Currently the feed-prpl CI build testing pipeline suddenly fails:

  $ pip3 install jinja2
  error: externally-managed-environment
  This environment is externally managed
  ╰─>
    The system-wide python installation should be maintained using the system
    package manager (apk) only.
  ...

Thats because we’re using latest Alpine Linux containers and those get
update to latest Alpine Linux 3.19.0 release just a few days ago on
December 7th, 2023 with following note related to the above in the
release notes:

  Python’s package directory is now marked as externally managed, which
  means that pip can no longer install to system directory which is
  managed by apk.

So lets fix it by using jinja2 apk package directly as suggested.

Fixes: PCF-1055
References: https://www.alpinelinux.org/posts/Alpine-3.19.0-released.html
Signed-off-by: Petr Štetiar <ynezz@true.cz>