PROVISORY: profiles: qca_ipq95xx: workaround a bunch of build race issues in qca-nss-ppe packages
We're currently seeing a lot of build failures around packages utilizing
ppe_*.h C include headers from staging directory.

In file included from linux-ipq95xx_generic/qca-nss-ppe-ds-51442d1aa846dc8a495e5ed8e845f92545be05a7/drv/ppe_ds/ppe_ds.h:22,
                 from linux-ipq95xx_generic/qca-nss-ppe-ds-51442d1aa846dc8a495e5ed8e845f92545be05a7/drv/ppe_ds/ppe_ds_stats.h:22,
                 from linux-ipq95xx_generic/qca-nss-ppe-ds-51442d1aa846dc8a495e5ed8e845f92545be05a7/drv/ppe_ds/ppe_ds_main.c:20:
                 linux-ipq95xx_generic/qca-nss-ppe-ds-51442d1aa846dc8a495e5ed8e845f92545be05a7/drv/ppe_ds/exports/ppe_ds_wlan.h:24:10: fatal error: ppe_vp_public.h

This is happening due to race conditions between several qca-nss-ppe-*
packages as they're installing the same C header files:

 find build_dir/ -name ppe_vp_public.h
 build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/linux-ipq95xx_generic/qca-nss-ppe-51442d1aa846dc8a495e5ed8e845f92545be05a7/drv/exports/ppe_vp_public.h
 build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/linux-ipq95xx_generic/qca-nss-ppe-qdisc-51442d1aa846dc8a495e5ed8e845f92545be05a7/drv/exports/ppe_vp_public.h
 build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/linux-ipq95xx_generic/qca-nss-ppe-vp-51442d1aa846dc8a495e5ed8e845f92545be05a7/drv/exports/ppe_vp_public.h
 build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/linux-ipq95xx_generic/qca-nss-ppe-ds-51442d1aa846dc8a495e5ed8e845f92545be05a7/drv/exports/ppe_vp_public.h
 build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/linux-ipq95xx_generic/qca-nss-ppe-rule-51442d1aa846dc8a495e5ed8e845f92545be05a7/drv/exports/ppe_vp_public.h
 build_dir/target-aarch64_cortex-a73+neon-vfpv4_musl/linux-ipq95xx_generic/qca-nss-ppe-clients-51442d1aa846dc8a495e5ed8e845f92545be05a7/drv/exports/ppe_vp_public.h

Until this is fixed properly, lets workaround it with various band aids.

References: PCF-1967, PPM-3491
Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>