ci: sdk: attempt to fix repository cloning issues
It seems like cloning from GitLab mirrored package feed repositories
started to fail heavily recently:

 Updating feed 'luci' from 'https://gitlab.com/openwrt/project/luci.git^f3debdcfd9a27202106032d988242c132f4c5f57' ...
 Cloning into './feeds/luci'...
 error: RPC failed; HTTP 500 curl 22 The requested URL returned error: 500

Attempt to workaround it by imposing some random delay before cloning of
the package feeds.

Signed-off-by: Petr Štetiar <ynezz@true.cz>
(cherry picked from commit 78c8f5b6b2cfe513fab3424d8e21608e6cb3b298)